### ISSUE TITLE
Add manpage

### ISSUE THREAD

**Issue by cappe987** [cappe987/hexend#4]
Add manpage for `hexend(1)`

If possible, add it to the build/install as well. Should it be included in `make all`? Or separate as `make doc`? Does it get included in normal `make install` as well?

**Comment by Mango0x45** [comment]
It should really just be included in `make install`, pretty sure thats the standard thing people do.

**Comment by cappe987** [comment]
Manpage added in PR #5. Issue still open for adding it to `make install` through CMake.

**Comment by yunsuklee** [comment]
Hey! May I be assigned this issue?

**Comment by Mango0x45** [comment]
#9 adds it to `make install` via CMake

**Comment by cappe987** [comment]
Thanks!
